/*
 * Most trace_* events are stubbed to no-ops in this trimmed lib. A select few
 * are wired to atomic counters via qcow2-counters for quantitative comparison
 * between runs (slow vs fast machine). See qemu/qcow2-counters.h.
 *
 * To wire an additional event: search for its #define below and replace the
 *   do {} while(0)
 * by
 *   QCOW2_COUNTER_INC(<name>)
 * then add the counter in qcow2-counters.{h,c}.
 */
#include "qemu/qcow2-counters.h"

#define trace_hd_geometry_lchs_guess(...) do {} while(0)
#define trace_hd_geometry_guess(...) do {} while(0)
#define trace_qcrypto_tls_session_new(...) do {} while(0)
#define trace_qcrypto_tls_session_check_creds(...) do {} while(0)
#define trace_qcrypto_tls_session_check_creds(...) do {} while(0)
#define trace_qcrypto_tls_session_check_creds(...) do {} while(0)
#define trace_qcrypto_tls_session_check_creds(...) do {} while(0)
#define trace_qcrypto_tls_session_check_creds(...) do {} while(0)
#define trace_qcrypto_tls_creds_load_dh(...) do {} while(0)
#define trace_qcrypto_tls_creds_get_path(...) do {} while(0)
#define trace_qcow2_cache_entry_flush(...) do {} while(0)
#define trace_qcow2_cache_flush(...) do {} while(0)
#define trace_qcow2_cache_get(...) QCOW2_COUNTER_INC(cache_get)
#define trace_qcow2_cache_get_replace_entry(...) QCOW2_COUNTER_INC(cache_get_replace_entry)
#define trace_qcow2_cache_get_read(...) QCOW2_COUNTER_INC(cache_get_read)
#define trace_qcow2_cache_get_done(...) do {} while(0)
#define trace_qcow2_process_discards_failed_region(...) do {} while(0)
#define trace_qemu_mutex_lock(...) QCOW2_COUNTER_INC(mutex_lock)
#define trace_qemu_mutex_locked(...) QCOW2_COUNTER_INC(mutex_locked)
#define trace_qemu_mutex_unlock(...) QCOW2_COUNTER_INC(mutex_unlock)
#define trace_socket_listen(...) do {} while(0)
#define trace_qemu_aio_coroutine_enter(...) QCOW2_COUNTER_INC(coroutine_enter)
#define trace_qemu_coroutine_terminate(...) QCOW2_COUNTER_INC(coroutine_terminate)
#define trace_qemu_coroutine_yield(...) QCOW2_COUNTER_INC(coroutine_yield)
#define trace_poll_add(...) do {} while(0)
#define trace_poll_remove(...) do {} while(0)
#define trace_run_poll_handlers_begin(...) QCOW2_COUNTER_INC(run_poll_handlers_begin)
#define trace_run_poll_handlers_end(...) QCOW2_COUNTER_INC(run_poll_handlers_end)
#define trace_poll_shrink(...) QCOW2_COUNTER_INC(poll_shrink)
#define trace_poll_grow(...) QCOW2_COUNTER_INC(poll_grow)
#define trace_hbitmap_iter_skip_words(...) do {} while(0)
#define trace_hbitmap_set(...) do {} while(0)
#define trace_hbitmap_reset(...) do {} while(0)
#define trace_thread_pool_complete(...) QCOW2_COUNTER_INC(thread_pool_complete)
#define trace_thread_pool_cancel(...) do {} while(0)
#define trace_thread_pool_submit(...) QCOW2_COUNTER_INC(thread_pool_submit)
#define trace_aio_co_schedule_bh_cb(...) QCOW2_COUNTER_INC(aio_co_schedule_bh_cb)
#define trace_aio_co_schedule(...) QCOW2_COUNTER_INC(aio_co_schedule)
#define trace_module_load_module(...) do {} while(0)
#define trace_module_lookup_object_type(...) do {} while(0)
#define trace_lockcnt_fast_path_attempt(...) QCOW2_COUNTER_INC(lockcnt_fast_path_attempt)
#define trace_lockcnt_fast_path_success(...) QCOW2_COUNTER_INC(lockcnt_fast_path_success)
#define trace_lockcnt_futex_wait_prepare(...) do {} while(0)
#define trace_lockcnt_futex_wait(...) QCOW2_COUNTER_INC(lockcnt_futex_wait)
#define trace_lockcnt_futex_wait_resume(...) do {} while(0)
#define trace_lockcnt_futex_wake(...) do {} while(0)
#define trace_lockcnt_unlock_attempt(...) do {} while(0)
#define trace_lockcnt_unlock_success(...) do {} while(0)
#define trace_lockcnt_unlock_attempt(...) do {} while(0)
#define trace_lockcnt_unlock_success(...) do {} while(0)
#define trace_qemu_aio_coroutine_enter(...) QCOW2_COUNTER_INC(coroutine_enter)
#define trace_qemu_coroutine_terminate(...) QCOW2_COUNTER_INC(coroutine_terminate)
#define trace_qemu_coroutine_yield(...) QCOW2_COUNTER_INC(coroutine_yield)
#define trace_qemu_memalign(...) do {} while(0)
#define trace_qemu_vfree(...) do {} while(0)
#define trace_qemu_co_mutex_lock_entry(...) QCOW2_COUNTER_INC(co_mutex_lock_entry)
#define trace_qemu_co_mutex_lock_return(...) QCOW2_COUNTER_INC(co_mutex_lock_return)
#define trace_qemu_co_mutex_lock_uncontended(...) QCOW2_COUNTER_INC(co_mutex_lock_uncontended)
#define trace_qemu_co_mutex_unlock_entry(...) QCOW2_COUNTER_INC(co_mutex_unlock_entry)
#define trace_qemu_co_mutex_unlock_return(...) QCOW2_COUNTER_INC(co_mutex_unlock_return)
#define trace_qemu_mutex_unlock(...) QCOW2_COUNTER_INC(mutex_unlock)
#define trace_qemu_mutex_locked(...) QCOW2_COUNTER_INC(mutex_locked)
#define trace_qmp_job_cancel(...) do {} while(0)
#define trace_qmp_job_pause(...) do {} while(0)
#define trace_qmp_job_resume(...) do {} while(0)
#define trace_qmp_job_complete(...) do {} while(0)
#define trace_qmp_job_finalize(...) do {} while(0)
#define trace_qmp_job_dismiss(...) do {} while(0)
#define trace_nbd_client_handshake_success(...) do {} while(0)
#define trace_nbd_reconnect_attempt(...) do {} while(0)
#define trace_nbd_reconnect_attempt_result(...) do {} while(0)
#define trace_nbd_structured_read_compliance(...) do {} while(0)
#define trace_nbd_parse_blockstatus_compliance(...) do {} while(0)
#define trace_nbd_parse_blockstatus_compliance(...) do {} while(0)
#define trace_nbd_parse_blockstatus_compliance(...) do {} while(0)
#define trace_nbd_structured_read_compliance(...) do {} while(0)
#define trace_nbd_extended_headers_compliance(...) do {} while(0)
#define trace_bdrv_co_do_copy_on_readv(...) do {} while(0)
#define trace_bdrv_co_preadv_part(...) QCOW2_COUNTER_INC(bdrv_co_preadv)
#define trace_bdrv_co_pwritev_part(...) QCOW2_COUNTER_INC(bdrv_co_pwritev)
#define trace_bdrv_co_pwrite_zeroes(...) do {} while(0)
#define trace_bdrv_co_copy_range_from(...) do {} while(0)
#define trace_bdrv_co_copy_range_to(...) do {} while(0)
#define trace_commit_one_iteration(...) do {} while(0)
#define trace_commit_start(...) do {} while(0)
#define trace_mirror_start(...) do {} while(0)
#define trace_file_flush_fdatasync_failed(...) do {} while(0)
#define trace_file_copy_file_range(...) do {} while(0)
#define trace_zbd_zone_append_complete(...) do {} while(0)
#define trace_zbd_zone_report(...) do {} while(0)
#define trace_zbd_zone_mgmt(...) do {} while(0)
#define trace_zbd_zone_append(...) do {} while(0)
#define trace_file_FindEjectableOpticalMedia(...) do {} while(0)
#define trace_file_setup_cdrom(...) do {} while(0)
#define trace_file_hdev_is_sg(...) do {} while(0)
#define trace_blk_root_attach(...) do {} while(0)
#define trace_blk_root_detach(...) do {} while(0)
#define trace_blk_co_preadv(...) do {} while(0)
#define trace_blk_co_pwritev(...) do {} while(0)
#define trace_job_state_transition(...) do {} while(0)
#define trace_job_apply_verb(...) do {} while(0)
#define trace_job_completed(...) do {} while(0)
#define trace_nbd_send_option_request(...) do {} while(0)
#define trace_nbd_receive_list(...) do {} while(0)
#define trace_nbd_opt_info_go_start(...) do {} while(0)
#define trace_nbd_opt_info_go_success(...) do {} while(0)
#define trace_nbd_receive_negotiate_size_flags(...) do {} while(0)
#define trace_nbd_opt_info_block_size(...) do {} while(0)
#define trace_nbd_opt_info_unknown(...) do {} while(0)
#define trace_nbd_receive_query_exports_start(...) do {} while(0)
#define trace_nbd_receive_query_exports_success(...) do {} while(0)
#define trace_nbd_receive_starttls_new_client(...) do {} while(0)
#define trace_nbd_receive_starttls_tls_handshake(...) do {} while(0)
#define trace_nbd_opt_meta_request(...) do {} while(0)
#define trace_nbd_opt_meta_reply(...) do {} while(0)
#define trace_nbd_start_negotiate(...) do {} while(0)
#define trace_nbd_receive_negotiate_magic(...) do {} while(0)
#define trace_nbd_receive_negotiate_magic(...) do {} while(0)
#define trace_nbd_receive_negotiate_server_flags(...) do {} while(0)
#define trace_nbd_receive_negotiate_name(...) do {} while(0)
#define trace_nbd_receive_negotiate_size_flags(...) do {} while(0)
#define trace_nbd_init_set_socket(...) do {} while(0)
#define trace_nbd_init_set_block_size(...) do {} while(0)
#define trace_nbd_init_set_size(...) do {} while(0)
#define trace_nbd_init_trailing_bytes(...) do {} while(0)
#define trace_nbd_init_set_readonly(...) do {} while(0)
#define trace_nbd_init_finish(...) do {} while(0)
#define trace_nbd_client_loop(...) do {} while(0)
#define trace_nbd_client_loop_ret(...) do {} while(0)
#define trace_nbd_client_clear_queue(...) do {} while(0)
#define trace_nbd_client_clear_socket(...) do {} while(0)
#define trace_nbd_receive_wrong_header(...) do {} while(0)
#define trace_nbd_unknown_error(...) do {} while(0)
#define trace_nbd_connect_thread_sleep(...) do {} while(0)
#define trace_bdrv_open_common(...) do {} while(0)
#define trace_bdrv_lock_medium(...) do {} while(0)
#define trace_qauthz_is_allowed(...) do {} while(0)
#define trace_visit_complete(...) do {} while(0)
#define trace_visit_free(...) do {} while(0)
#define trace_visit_start_struct(...) do {} while(0)
#define trace_visit_check_struct(...) do {} while(0)
#define trace_visit_end_struct(...) do {} while(0)
#define trace_visit_start_list(...) do {} while(0)
#define trace_visit_next_list(...) do {} while(0)
#define trace_visit_check_list(...) do {} while(0)
#define trace_visit_end_list(...) do {} while(0)
#define trace_visit_start_alternate(...) do {} while(0)
#define trace_visit_end_alternate(...) do {} while(0)
#define trace_visit_optional(...) do {} while(0)
#define trace_visit_policy_reject(...) do {} while(0)
#define trace_visit_policy_skip(...) do {} while(0)
#define trace_visit_type_int(...) do {} while(0)
#define trace_visit_type_uint8(...) do {} while(0)
#define trace_visit_type_uint16(...) do {} while(0)
#define trace_visit_type_uint32(...) do {} while(0)
#define trace_visit_type_uint64(...) do {} while(0)
#define trace_visit_type_int8(...) do {} while(0)
#define trace_visit_type_int16(...) do {} while(0)
#define trace_visit_type_int32(...) do {} while(0)
#define trace_visit_type_int64(...) do {} while(0)
#define trace_visit_type_size(...) do {} while(0)
#define trace_visit_type_bool(...) do {} while(0)
#define trace_visit_type_str(...) do {} while(0)
#define trace_visit_type_number(...) do {} while(0)
#define trace_visit_type_any(...) do {} while(0)
#define trace_visit_type_null(...) do {} while(0)
#define trace_visit_type_enum(...) do {} while(0)
#define trace_qcow2_add_task(...) do {} while(0)
#define trace_qcow2_skip_cow(...) do {} while(0)
#define trace_qcow2_writev_data(...) do {} while(0)
#define trace_qcow2_writev_start_req(...) do {} while(0)
#define trace_qcow2_writev_start_part(...) do {} while(0)
#define trace_qcow2_writev_done_part(...) do {} while(0)
#define trace_qcow2_writev_done_req(...) do {} while(0)
#define trace_qcow2_pwrite_zeroes_start_req(...) do {} while(0)
#define trace_qcow2_pwrite_zeroes(...) do {} while(0)
#define trace_qcow2_writev_done_req(...) do {} while(0)
#define trace_qio_channel_file_new_fd(...) do {} while(0)
#define trace_qio_channel_file_new_path(...) do {} while(0)
#define trace_qio_channel_socket_new(...) do {} while(0)
#define trace_qio_channel_socket_new_fd(...) do {} while(0)
#define trace_qio_channel_socket_connect_sync(...) do {} while(0)
#define trace_qio_channel_socket_connect_fail(...) do {} while(0)
#define trace_qio_channel_socket_connect_complete(...) do {} while(0)
#define trace_qio_channel_socket_connect_async(...) do {} while(0)
#define trace_qio_channel_socket_listen_sync(...) do {} while(0)
#define trace_qio_channel_socket_listen_fail(...) do {} while(0)
#define trace_qio_channel_socket_listen_complete(...) do {} while(0)
#define trace_qio_channel_socket_listen_async(...) do {} while(0)
#define trace_qio_channel_socket_dgram_sync(...) do {} while(0)
#define trace_qio_channel_socket_dgram_fail(...) do {} while(0)
#define trace_qio_channel_socket_dgram_complete(...) do {} while(0)
#define trace_qio_channel_socket_dgram_async(...) do {} while(0)
#define trace_qio_channel_socket_accept(...) do {} while(0)
#define trace_qio_channel_socket_accept_fail(...) do {} while(0)
#define trace_qio_channel_socket_accept_complete(...) do {} while(0)
#define trace_qio_channel_tls_new_server(...) do {} while(0)
#define trace_qio_channel_tls_new_client(...) do {} while(0)
#define trace_qio_channel_tls_handshake_fail(...) do {} while(0)
#define trace_qio_channel_tls_handshake_complete(...) do {} while(0)
#define trace_qio_channel_tls_credentials_deny(...) do {} while(0)
#define trace_qio_channel_tls_credentials_allow(...) do {} while(0)
#define trace_qio_channel_tls_handshake_pending(...) do {} while(0)
#define trace_qio_channel_tls_handshake_start(...) do {} while(0)
#define trace_qio_channel_tls_handshake_cancel(...) do {} while(0)
#define trace_qio_task_new(...) do {} while(0)
#define trace_qio_task_thread_result(...) do {} while(0)
#define trace_qio_task_thread_run(...) do {} while(0)
#define trace_qio_task_thread_exit(...) do {} while(0)
#define trace_qio_task_thread_source_attach(...) do {} while(0)
#define trace_qio_task_thread_start(...) do {} while(0)
#define trace_qio_task_thread_source_cancel(...) do {} while(0)
#define trace_qio_task_complete(...) do {} while(0)
#define trace_qcow2_l2_allocate(...) do {} while(0)
#define trace_qcow2_l2_allocate_get_empty(...) do {} while(0)
#define trace_qcow2_l2_allocate_write_l2(...) do {} while(0)
#define trace_qcow2_l2_allocate_write_l1(...) do {} while(0)
#define trace_qcow2_l2_allocate_done(...) do {} while(0)
#define trace_qcow2_l2_allocate_done(...) do {} while(0)
#define trace_qcow2_cluster_link_l2(...) do {} while(0)
#define trace_qcow2_handle_copied(...) do {} while(0)
#define trace_qcow2_do_alloc_clusters_offset(...) do {} while(0)
#define trace_qcow2_cluster_alloc_phys(...) do {} while(0)
#define trace_qcow2_handle_alloc(...) do {} while(0)
#define trace_qcow2_alloc_clusters_offset(...) do {} while(0)
#define trace_opt_parse(...) do {} while(0)
#define trace_init_file(...) do {} while(0)
#define trace_nbd_receive_option_reply(...) do {} while(0)
#define trace_nbd_server_error_msg(...) do {} while(0)
#define trace_nbd_reply_err_ignored(...) do {} while(0)
#define trace_nbd_send_request(...) do {} while(0)
#define trace_nbd_receive_simple_reply(...) do {} while(0)
#define trace_nbd_receive_reply_chunk_header(...) do {} while(0)
#define trace_nbd_co_request_fail(...) do {} while(0)
#define trace_reentrant_aio(...) do {} while(0)
#define trace_mirror_before_flush(...) do {} while(0)
#define trace_mirror_before_drain(...) do {} while(0)
#define trace_mirror_before_sleep(...) do {} while(0)
#define trace_mirror_restart_iter(...) do {} while(0)
#define trace_mirror_one_iteration(...) do {} while(0)
#define trace_mirror_yield_in_flight(...) do {} while(0)
#define trace_mirror_yield(...) do {} while(0)
#define trace_mirror_iteration_done(...) do {} while(0)
#define trace_object_dynamic_cast_assert(...) do {} while(0)
#define trace_object_class_dynamic_cast_assert(...) do {} while(0)
